# Generated by Django 4.2.7 on 2024-08-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='EmailAccount',
        ),
        migrations.DeleteModel(
            name='EmailBody',
        ),
        migrations.DeleteModel(
            name='EmailSubject',
        ),
        migrations.DeleteModel(
            name='SentEmailLog',
        ),
    ]
