# Generated by Django 4.2.7 on 2024-08-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentEmailLog',
        ),
    ]
